# Generated by Django 3.2.2 on 2021-05-17 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arg1', models.FloatField()),
                ('arg2', models.FloatField()),
                ('operation_name', models.CharField(max_length=12)),
                ('result', models.FloatField()),
                ('performed', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Arg',
        ),
    ]
